set-option -g default-shell /bin/zsh  # Change to your preferred shell path
set-option -sa terminal-overrides ",xterm*:Tc"

# remap prefix from 'C-b' to 'C-Space'
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-arrow keys without prefix to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g status-style "bg=terminal"
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Enable focus tracking
set -g focus-events on

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Enable 256-Color Support
set -g default-terminal "tmux-256color"

# 2. Force UTF‑8 for any client that attaches
set -ga terminal-overrides ',*:UTF-8'

# 3. (Nice to have) enable true‑colour
set -ga terminal-overrides ',xterm-256color:Tc'

# don't rename windows automatically
set-option -g allow-rename off

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'b1o/tmux-autoreload'

set -g @plugin 'catppuccin/tmux#v2.3.0'

# Configure cattpuccin
set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_background "#242638" 
# set -g @catppuccin_window_current_text "#T"
# set -g @catppuccin_window_text "#T"
set -g @catppuccin_window_current_text "#T"
set -g @catppuccin_window_text "#{b:pane_current_path}"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -gF window-status-separator ""
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -g @catppuccin_window_current_number_color "#{@thm_peach}"

# Pane border look/feel
setw -g pane-border-status top
# setw -g pane-border-format "#{}"
setw -g pane-active-border-style "bg=#{@thm_bg},fg=#{@thm_overlay_0}"
setw -g pane-border-style "bg=#{@thm_bg},fg=#{@thm_surface_0}"
setw -g pane-border-lines single

set-window-option -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
